server:
  port: 8081
management:
  security:
    enabled: true
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ngmember?autoReconnect=true&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      pool-name: springBootHikariPool
      maximum-pool-size: 10
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 127.0.0.1
mybatis:
  type-aliases-package: com.ng.member.entity
  mapper-locations: classpath:mapper/*.xml
mapper:
  identity: MYSQL
  not-empty: false
  mappers:
      - MyMapper
pagehelper:
  helper-dialect: mysql
  reasonable: true
  # issue https://github.com/pagehelper/pagehelper-spring-boot/issues/25
  support-methods-arguments: !!str true
  offset-as-page-num: !!str true
  row-bounds-with-count: !!str true